In [5]:
import pandas as pd
import numpy as np
import os,glob

In [2]:
RAW_FILE = r"C:\Users\ridge\Downloads\Crimes_-_2001_to_Present.csv"

In [3]:
## DO NOT CHANGE THIS CELL
if RAW_FILE == r"YOUR FILEPATH HERE":
	raise Exception("You must update the RAW_FILE variable in the previous cell to match your local filepath.")
	
RAW_FILE

'C:\\Users\\ridge\\Downloads\\Crimes_-_2001_to_Present.csv'

In [6]:
# (Optional) SET THE FOLDER FOR FINAL FILES
OUTPUT_FOLDER = 'Data/Chicago/'
os.makedirs(OUTPUT_FOLDER, exist_ok=True)

In [7]:
chicago_full = pd.read_csv(RAW_FILE)
chicago_full

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,...,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
0,11646166,JC213529,09/01/2018 12:01:00 AM,082XX S INGLESIDE AVE,0810,THEFT,OVER $500,RESIDENCE,False,True,...,8.0,44.0,06,NaN,NaN,2018,04/06/2019 04:04:43 PM,NaN,NaN,NaN
1,11645836,JC212333,05/01/2016 12:25:00 AM,055XX S ROCKWELL ST,1153,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT OVER $ 300,NaN,False,False,...,15.0,63.0,11,NaN,NaN,2016,04/06/2019 04:04:43 PM,NaN,NaN,NaN
2,11243268,JB167760,01/01/2017 12:01:00 AM,047XX N CLARK ST,1562,SEX OFFENSE,AGG CRIMINAL SEXUAL ABUSE,APARTMENT,False,False,...,47.0,3.0,17,NaN,NaN,2017,09/13/2018 03:56:52 PM,NaN,NaN,NaN
3,1896258,G749215,12/15/2001 02:00:00 AM,011XX N STATE ST,0460,BATTERY,SIMPLE,STREET,False,False,...,NaN,NaN,08B,NaN,NaN,2001,08/17/2015 03:03:40 PM,NaN,NaN,NaN
4,11645527,JC212744,02/02/2015 10:00:00 AM,069XX W ARCHER AVE,1153,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT OVER $ 300,OTHER,False,False,...,23.0,56.0,11,NaN,NaN,2015,04/06/2019 04:04:43 PM,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7880189,13128007,JG325985,06/21/2023 08:00:00 PM,031XX N CALIFORNIA AVE,1320,CRIMINAL DAMAGE,TO VEHICLE,STREET,False,False,...,35.0,21.0,14,1157169.0,1920611.0,2023,08/19/2023 03:40:26 PM,41.937926,-87.697782,"(41.937925817, -87.697782474)"
7880190,13128324,JG326502,05/13/2023 12:00:00 PM,020XX W CERMAK RD,1120,DECEPTIVE PRACTICE,FORGERY,CURRENCY EXCHANGE,False,False,...,25.0,31.0,10,1163211.0,1889404.0,2023,08/19/2023 03:40:26 PM,41.852166,-87.676455,"(41.85216632, -87.676455032)"
7880191,13128375,JG326564,06/24/2023 01:29:00 PM,069XX N HAMILTON AVE,1330,CRIMINAL TRESPASS,TO LAND,RESIDENCE,False,False,...,40.0,2.0,26,1160740.0,1946176.0,2023,08/19/2023 03:40:26 PM,42.008004,-87.683946,"(42.008003927, -87.683946124)"
7880192,13129172,JG327619,06/20/2023 04:00:00 AM,028XX N MAPLEWOOD AVE,0460,BATTERY,SIMPLE,RESIDENCE,False,True,...,35.0,21.0,08B,1158868.0,1918755.0,2023,08/19/2023 03:40:26 PM,41.932798,-87.691589,"(41.932798095, -87.691589364)"
7880193,13129823,JG328250,06/28/2023 06:00:00 PM,059XX S KEELER AVE,0810,THEFT,OVER $500,STREET,False,False,...,13.0,65.0,06,1149387.0,1864869.0,2023,08/19/2023 03:40:26 PM,41.785118,-87.727828,"(41.785117789, -87.727827896)"

In [8]:
# this cell can take up to 1 min to run
date_format = "%m/%d/%Y %H:%M:%S %p"

chicago_full['Datetime'] = pd.to_datetime(chicago_full['Date'], format=date_format)
chicago_full = chicago_full.sort_values('Datetime')
chicago_full

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,...,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location,Datetime
2452465,1315701,G003835,01/01/2001 01:00:00 PM,011XX S PULASKI RD,041A,BATTERY,AGGRAVATED: HANDGUN,RESIDENCE,False,False,...,NaN,04B,1149936.0,1894501.0,2001,08/17/2015 03:03:40 PM,41.866421,-87.725046,"(41.866421432, -87.72504577)",2001-01-01 01:00:00
2450630,1309918,G000412,01/01/2001 01:00:00 AM,032XX N SHEFFIELD AV,0820,THEFT,$500 AND UNDER,TAVERN/LIQUOR STORE,False,False,...,NaN,06,1169005.0,1921458.0,2001,08/17/2015 03:03:40 PM,41.940001,-87.654258,"(41.940000996, -87.654258339)",2001-01-01 01:00:00
2450774,1310858,G001441,01/01/2001 01:00:00 PM,032XX W BELLE PLAINE AV,2820,OTHER OFFENSE,TELEPHONE THREAT,RESIDENCE,False,False,...,NaN,26,1154092.0,1927036.0,2001,08/17/2015 03:03:40 PM,41.955619,-87.708919,"(41.955618511, -87.708919081)",2001-01-01 01:00:00
2462863,1333483,G032501,01/01/2001 01:00:00 PM,025XX W 119 ST,1320,CRIMINAL DAMAGE,TO VEHICLE,STREET,False,False,...,NaN,14,1161850.0,1825696.0,2001,08/17/2015 03:03:40 PM,41.677371,-87.683218,"(41.677370879, -87.683217554)",2001-01-01 01:00:00
2450766,1310824,G001340,01/01/2001 01:00:00 AM,071XX S MICHIGAN AV,0820,THEFT,$500 AND UNDER,BAR OR TAVERN,False,False,...,NaN,06,1178353.0,1857936.0,2001,08/17/2015 03:03:40 PM,41.765484,-87.621836,"(41.765484067, -87.621836295)",2001-01-01 01:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113407,13188860,JG398340,08/26/2023 12:00:00 AM,078XX S SOUTH SHORE DR,1320,CRIMINAL DAMAGE,TO VEHICLE,STREET,False,False,...,46.0,14,1198338.0,1853426.0,2023,09/02/2023 03:41:45 PM,41.752631,-87.548737,"(41.752631346, -87.548737069)",2023-08-26 12:00:00
113554,13195140,JG405355,08/26/2023 12:00:00 AM,018XX N Humboldt Blvd,0810,THEFT,OVER $500,STREET,False,False,...,22.0,06,NaN,NaN,2023,09/02/2023 03:41:45 PM,NaN,NaN,NaN,2023-08-26 12:00:00
113684,13188609,JG397992,08/26/2023 12:00:00 AM,0000X E WASHINGTON ST,0460,BATTERY,SIMPLE,APARTMENT,False,False,...,32.0,08B,1176912.0,1900830.0,2023,09/02/2023 03:41:45 PM,41.883221,-87.625823,"(41.883221363, -87.625823296)",2023-08-26 12:00:00
113630,13188551,JG397943,08/26/2023 12:00:00 AM,038XX W ROOSEVELT RD,0820,THEFT,$500 AND UNDER,SIDEWALK,False,True,...,29.0,06,1151056.0,1894439.0,2023,09/02/2023 03:41:45 PM,41.866229,-87.720936,"(41.866229446, -87.720935733)",2023-08-26 12:00:00
113584,13192080,JG398100,08/26/2023 12:00:00 AM,006XX S LA SALLE ST,1320,CRIMINAL DAMAGE,TO VEHICLE,STREET,False,False,...,32.0,14,1175346.0,1897439.0,2023,09/02/2023 03:41:45 PM,41.873952,-87.631675,"(41.873951538, -87.631675478)",2023-08-26 12:00:00

## Separate the Full Dataset by Years

In [9]:
chicago_full['Datetime'].dt.year

2452465    2001
2450630    2001
2450774    2001
2462863    2001
2450766    2001
           ...
113407     2023
113554     2023
113684     2023
113630     2023
113584     2023
Name: Datetime, Length: 7880194, dtype: int64

In [10]:
# save the years for every crime
chicago_full["Year"] = chicago_full['Datetime'].dt.year.astype(str)
chicago_full["Year"].value_counts()

2002    486807
2001    485886
2003    475985
2004    469422
2005    453773
2006    448179
2007    437087
2008    427183
2009    392827
2010    370514
2011    351993
2012    336319
2013    307537
2014    275789
2016    269823
2017    269102
2018    268900
2015    264788
2019    261329
2022    238875
2020    212199
2021    208825
2023    167052
Name: Year, dtype: int64

In [11]:
## Dropping unneeded columns to reduce file size
drop_cols = ["X Coordinate","Y Coordinate", "Community Area","FBI Code",
             "Case Number","Updated On",'Block','Location','IUCR']

In [12]:
# save final df
chicago_final = chicago_full.drop(columns=drop_cols)
chicago_final = chicago_final.set_index('Datetime')
chicago_final

,ID,Date,Primary Type,Description,Location Description,Arrest,Domestic,Beat,District,Ward,Year,Latitude,Longitude
Datetime,,,,,,,,,,,,,
2001-01-01 01:00:00,1315701,01/01/2001 01:00:00 PM,BATTERY,AGGRAVATED: HANDGUN,RESIDENCE,False,False,1132,11.0,NaN,2001,41.866421,-87.725046
2001-01-01 01:00:00,1309918,01/01/2001 01:00:00 AM,THEFT,$500 AND UNDER,TAVERN/LIQUOR STORE,False,False,1924,19.0,NaN,2001,41.940001,-87.654258
2001-01-01 01:00:00,1310858,01/01/2001 01:00:00 PM,OTHER OFFENSE,TELEPHONE THREAT,RESIDENCE,False,False,1724,17.0,NaN,2001,41.955619,-87.708919
2001-01-01 01:00:00,1333483,01/01/2001 01:00:00 PM,CRIMINAL DAMAGE,TO VEHICLE,STREET,False,False,2212,22.0,NaN,2001,41.677371,-87.683218
2001-01-01 01:00:00,1310824,01/01/2001 01:00:00 AM,THEFT,$500 AND UNDER,BAR OR TAVERN,False,False,323,3.0,NaN,2001,41.765484,-87.621836
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-08-26 12:00:00,13188860,08/26/2023 12:00:00 AM,CRIMINAL DAMAGE,TO VEHICLE,STREET,False,False,421,4.0,7.0,2023,41.752631,-87.548737
2023-08-26 12:00:00,13195140,08/26/2023 12:00:00 AM,THEFT,OVER $500,STREET,False,False,1421,14.0,26.0,2023,NaN,NaN
2023-08-26 12:00:00,13188609,08/26/2023 12:00:00 AM,BATTERY,SIMPLE,APARTMENT,False,False,112,1.0,34.0,2023,41.883221,-87.625823
2023-08-26 12:00:00,13188551,08/26/2023 12:00:00 AM,THEFT,$500 AND UNDER,SIDEWALK,False,True,1011,10.0,24.0,2023,41.866229,-87.720936
2023-08-26 12:00:00,13192080,08/26/2023 12:00:00 AM,CRIMINAL DAMAGE,TO VEHICLE,STREET,False,False,123,1.0,34.0,2023,41.873952,-87.631675

In [13]:
# unique # of year bins
year_bins = chicago_final['Year'].astype(str).unique()
year_bins

array(['2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008',
       '2009', '2010', '2011', '2012', '2013', '2014', '2015', '2016',
       '2017', '2018', '2019', '2020', '2021', '2022', '2023'],
      dtype=object)

In [14]:
FINAL_DROP = ['Year']

In [15]:
## set save location 

os.makedirs(OUTPUT_FOLDER, exist_ok=True)
print(f"[i] Saving .csv's to {OUTPUT_FOLDER}")
## loop through years
for year in year_bins:
    
    ## save temp slices of dfs to save.
    temp_df = chicago_final.loc[year]
    temp_df = temp_df.sort_index()
    temp_df = temp_df.reset_index(drop=True)
    temp_df = temp_df.drop(columns=FINAL_DROP)

    # save as csv to output folder
    fname_temp = f"{OUTPUT_FOLDER}Chicago-Crime_{year}.csv"#.gz
    temp_df.to_csv(fname_temp,index=False)

    print(f"- Succesfully saved {fname_temp}")

[i] Saving .csv's to Data/Chicago/
- Succesfully saved Data/Chicago/Chicago-Crime_2001.csv
- Succesfully saved Data/Chicago/Chicago-Crime_2002.csv
- Succesfully saved Data/Chicago/Chicago-Crime_2003.csv
- Succesfully saved Data/Chicago/Chicago-Crime_2004.csv
- Succesfully saved Data/Chicago/Chicago-Crime_2005.csv
- Succesfully saved Data/Chicago/Chicago-Crime_2006.csv
- Succesfully saved Data/Chicago/Chicago-Crime_2007.csv
- Succesfully saved Data/Chicago/Chicago-Crime_2008.csv
- Succesfully saved Data/Chicago/Chicago-Crime_2009.csv
- Succesfully saved Data/Chicago/Chicago-Crime_2010.csv
- Succesfully saved Data/Chicago/Chicago-Crime_2011.csv
- Succesfully saved Data/Chicago/Chicago-Crime_2012.csv
- Succesfully saved Data/Chicago/Chicago-Crime_2013.csv
- Succesfully saved Data/Chicago/Chicago-Crime_2014.csv
- Succesfully saved Data/Chicago/Chicago-Crime_2015.csv
- Succesfully saved Data/Chicago/Chicago-Crime_2016.csv
- Succesfully saved Data/Chicago/Chicago-Crime_2017.csv
- Succesfully saved Data/Chicago/Chicago-Crime_2018.csv
- Succesfully saved Data/Chicago/Chicago-Crime_2019.csv
- Succesfully saved Data/Chicago/Chicago-Crime_2020.csv
- Succesfully saved Data/Chicago/Chicago-Crime_2021.csv
- Succesfully saved Data/Chicago/Chicago-Crime_2022.csv
- Succesfully saved Data/Chicago/Chicago-Crime_2023.csv

In [16]:
saved_files = sorted(glob.glob(OUTPUT_FOLDER+'*.*csv'))
saved_files

['Data/Chicago\\Chicago-Crime_2001.csv',
 'Data/Chicago\\Chicago-Crime_2002.csv',
 'Data/Chicago\\Chicago-Crime_2003.csv',
 'Data/Chicago\\Chicago-Crime_2004.csv',
 'Data/Chicago\\Chicago-Crime_2005.csv',
 'Data/Chicago\\Chicago-Crime_2006.csv',
 'Data/Chicago\\Chicago-Crime_2007.csv',
 'Data/Chicago\\Chicago-Crime_2008.csv',
 'Data/Chicago\\Chicago-Crime_2009.csv',
 'Data/Chicago\\Chicago-Crime_2010.csv',
 'Data/Chicago\\Chicago-Crime_2011.csv',
 'Data/Chicago\\Chicago-Crime_2012.csv',
 'Data/Chicago\\Chicago-Crime_2013.csv',
 'Data/Chicago\\Chicago-Crime_2014.csv',
 'Data/Chicago\\Chicago-Crime_2015.csv',
 'Data/Chicago\\Chicago-Crime_2016.csv',
 'Data/Chicago\\Chicago-Crime_2017.csv',
 'Data/Chicago\\Chicago-Crime_2018.csv',
 'Data/Chicago\\Chicago-Crime_2019.csv',
 'Data/Chicago\\Chicago-Crime_2020.csv',
 'Data/Chicago\\Chicago-Crime_2021.csv',
 'Data/Chicago\\Chicago-Crime_2022.csv',
 'Data/Chicago\\Chicago-Crime_2023.csv']

In [17]:
## create a README.txt for the zip files
readme = """Source URL: 
- https://data.cityofchicago.org/Public-Safety/Crimes-2001-to-Present/ijzp-q8t2
- Filtered for years 2000-Present.

Downloaded 07/18/2022
- Files are split into 1 year per file.

EXAMPLE USAGE:
>> import glob
>> import pandas as pd
>> folder = "Data/Chicago/"
>> crime_files = sorted(glob.glob(folder+"*.csv"))
>> df = pd.concat([pd.read_csv(f) for f in crime_files])
"""
print(readme)


with open(f"{OUTPUT_FOLDER}README.txt",'w') as f:
    f.write(readme)

Source URL:
- https://data.cityofchicago.org/Public-Safety/Crimes-2001-to-Present/ijzp-q8t2
- Filtered for years 2000-Present.

Downloaded 07/18/2022
- Files are split into 1 year per file.

EXAMPLE USAGE:
>> import glob
>> import pandas as pd
>> folder = "Data/Chicago/"
>> crime_files = sorted(glob.glob(folder+"*.csv"))
>> df = pd.concat([pd.read_csv(f) for f in crime_files])

## Confirmation

In [18]:
# get list of files from folder
crime_files = sorted(glob.glob(OUTPUT_FOLDER+"*.csv"))
df = pd.concat([pd.read_csv(f, nrows=5) for f in crime_files])
df

,ID,Date,Primary Type,Description,Location Description,Arrest,Domestic,Beat,District,Ward,Latitude,Longitude
0,1315701,01/01/2001 01:00:00 PM,BATTERY,AGGRAVATED: HANDGUN,RESIDENCE,False,False,1132,11.0,NaN,41.866421,-87.725046
1,1309918,01/01/2001 01:00:00 AM,THEFT,$500 AND UNDER,TAVERN/LIQUOR STORE,False,False,1924,19.0,NaN,41.940001,-87.654258
2,1310858,01/01/2001 01:00:00 PM,OTHER OFFENSE,TELEPHONE THREAT,RESIDENCE,False,False,1724,17.0,NaN,41.955619,-87.708919
3,1333483,01/01/2001 01:00:00 PM,CRIMINAL DAMAGE,TO VEHICLE,STREET,False,False,2212,22.0,NaN,41.677371,-87.683218
4,1310824,01/01/2001 01:00:00 AM,THEFT,$500 AND UNDER,BAR OR TAVERN,False,False,323,3.0,NaN,41.765484,-87.621836
...,...,...,...,...,...,...,...,...,...,...,...,...
0,12938745,01/01/2023 01:00:00 AM,BATTERY,DOMESTIC BATTERY SIMPLE,VEHICLE NON-COMMERCIAL,False,True,1932,19.0,32.0,41.936276,-87.668540
1,12939025,01/01/2023 01:00:00 PM,BURGLARY,HOME INVASION,APARTMENT,False,False,421,4.0,7.0,41.758449,-87.557184
2,12938564,01/01/2023 01:00:00 AM,CRIMINAL DAMAGE,TO VEHICLE,STREET,False,False,835,8.0,18.0,41.750153,-87.679372
3,12938763,01/01/2023 01:00:00 AM,ROBBERY,STRONG ARM - NO WEAPON,SIDEWALK,False,False,1833,18.0,2.0,41.896766,-87.622056
4,12938591,01/01/2023 01:00:00 AM,CRIMINAL DAMAGE,TO PROPERTY,RESIDENCE - GARAGE,False,False,1713,17.0,33.0,41.971086,-87.712217

In [19]:
years = df['Date'].map(lambda x: x.split()[0].split('/')[-1])
years.value_counts().sort_index()

2001    5
2002    5
2003    5
2004    5
2005    5
2006    5
2007    5
2008    5
2009    5
2010    5
2011    5
2012    5
2013    5
2014    5
2015    5
2016    5
2017    5
2018    5
2019    5
2020    5
2021    5
2022    5
2023    5
Name: Date, dtype: int64